### PR TITLE
Fork refresh

### PR DESCRIPTION
**Pull request by roaet**
Will not merge. Discussion PR for the fact I'm going to shove this into master in a little bit.

Discuss.

### CODE REVIEW

**Comment by roaet** [comment]
Updating this fork of upstream's python-neutronclient with applied patches to support roles and noauth in public cloud (required for our clients to work)

**Comment by tr3buchet** [comment]
what even is this?

**Comment by roaet** [comment]
Exactly what was discussed in the IRC. A refresh of the fork.

**Comment by tr3buchet** [comment]
hold on to your butts

**Pull request merged**
